repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
-   repo: https://github.com/betterleaks/betterleaks
    rev: v1.8.1
    hooks:
    - id: betterleaks
      name: Detect hardcoded secrets
      description: Detect hardcoded secrets using Betterleaks
      entry: betterleaks git --pre-commit --redact --staged --verbose
      language: golang
      pass_filenames: false
-   repo: local
    hooks:
    - id: prettier
      name: prettier
      entry: cd apps/mobile && bun format && cd ../..
      language: unsupported
