"""fix other non-nullable fields by labeling Optional in ORM model

Revision ID: 0848d2fbd4e2
Revises: b38a9813bcc8
Create Date: 2026-09-14 17:22:15.019310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0848d2fbd4e2"
down_revision: str | Sequence[str] | None = "b38a9813bcc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "custom_model_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "custom_model_instructions", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "human_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "human_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "custom_model_instructions", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "custom_model_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
