"""Revises document so that we retain the original filename as given by the user; also, makes usernames and email addresses unique

Revision ID: 25cc9479ea76
Revises: 9e39a1bb503e
Create Date: 2026-09-21 19:02:51.716939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25cc9479ea76"
down_revision: str | Sequence[str] | None = "9e39a1bb503e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
    )
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("documents", "original_file_name")
    # ### end Alembic commands ###
