"""update db

Revision ID: 3436487f903a
Revises: 917cb0326e8d
Create Date: 2026-09-14 16:21:07.822732

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "3436487f903a"
down_revision: str | Sequence[str] | None = "917cb0326e8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_chunks", sa.Column("line", sa.Integer(), nullable=False))
    op.add_column("document_chunks", sa.Column("column", sa.Integer(), nullable=False))
    op.add_column("document_chunks", sa.Column("offset", sa.Integer(), nullable=False))
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=VECTOR(dim=4096),
        type_=VECTOR(dim=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=VECTOR(dim=1024),
        type_=VECTOR(dim=4096),
        existing_nullable=False,
    )
    op.drop_column("document_chunks", "offset")
    op.drop_column("document_chunks", "column")
    op.drop_column("document_chunks", "line")
    # ### end Alembic commands ###
