"""Revises document chunks so that they use only the data already EASILY given by the AST

Revision ID: 9e39a1bb503e
Revises: 0848d2fbd4e2
Create Date: 2026-09-20 21:51:24.241764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e39a1bb503e"
down_revision: str | Sequence[str] | None = "0848d2fbd4e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "path_to_chunk")
    op.drop_column("document_chunks", "section_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("section_title", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "document_chunks",
        sa.Column("path_to_chunk", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
