"""should add all new tables

Revision ID: a76bb8a521a2
Revises: f3a71b46b6c6
Create Date: 2026-08-21 14:22:10.090129

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a76bb8a521a2"
down_revision: str | Sequence[str] | None = "f3a71b46b6c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
