"""fix non-nullable deletion date

Revision ID: b38a9813bcc8
Revises: 3436487f903a
Create Date: 2026-09-14 17:19:18.258219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b38a9813bcc8"
down_revision: str | Sequence[str] | None = "3436487f903a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "deletion_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "deletion_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
